version: '3.7'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8.0.36
    restart: always
    ports:
      - '3307:3306'
    environment:
      # - MYSQL_DATABASE=books1 
      - MYSQL_ROOT_PASSWORD=30102001
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: