version: '3.7'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      # if your secret key includes a dollar sign, $, then you need to add an additional dollar sign, $$
      - SECRET_KEY=django-insecure-f_1!t&g_w%$cj9)7xbg^*-z4r*6&$8lw7hokp$tgh+egzf5hg#f
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8.0.36
    restart: always
    ports:
      - '3307:3306'
    environment:
      # - MYSQL_DATABASE=books1 
      - MYSQL_ROOT_PASSWORD=30102001
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: